### PR TITLE
openvinotoolkit.org->openvino.ai

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
14:15:28  FILE: README.md
14:15:40  [✖] https://01.org/openvinotoolkit
14:15:40  [✖] https://01.org/openvisualcloud
14:15:40  [✖] https://01.org/openvisualcloud/documents/tutorial-build-and-run-ad-insertion-sample-public-cloud-or-local-machine

**Comment by Wovchena** [comment]
I know. I've just wrote you about it

**Comment by nignatovsky** [comment]
It might be useful to replace 3 broken links with these (or use webarchive versions):

- `https://01.org/openvinotoolkit` -> https://docs.openvino.ai/latest/index.html
- `https://01.org/openvisualcloud` -> https://www.intel.com/content/www/us/en/developer/articles/technical/open-visual-cloud.html
- `https://01.org/openvisualcloud/documents/tutorial-build-and-run-ad-insertion-sample-public-cloud-or-local-machine` -> https://github.com/OpenVisualCloud/Ad-Insertion-Sample/wiki/Tutorial:-Running-AD-Insertion-on-Public-Cloud

**Comment by Wovchena** [comment]
Thanks!

**Pull request merged**
