### PR TITLE
OV2.0 properties

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
adopt social_distance_demo to new properties syntax

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
wait for 2022.1.577 package update

**Comment by ivikhrev** [comment]
@vladimir-dudnik the remaining old config keys should be updated in corresponding PR's?

**Comment by vladimir-dudnik** [comment]
I found only two such cases, one was security_barrier_camera_demo, added these changes to corresponding PR and social_distance_demo. If I miss some cases we may add them there (just add appropriate commit)

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
not relevant issues with face-detection-0205, person-detection-0106 on python object_detection_demo
cc @akorobeinikov

**Pull request merged**
