### PR TITLE
segmentation_demo/python: remove the ability to set a custom color palette

### PR DESCRIPTION
**Pull request by IRDonch**
This feature is barely documented, not tested at all, and involves a gratuitous use of `eval`. It's also not present in the C++ version of the demo. I think it's unnecessary.

### CODE REVIEW

**Comment by IRDonch** [comment]
CC @akorobeinikov

**Comment by Wovchena** [comment]
There are two reasons to keep this feature:
> [model has 150 segmentation classes, I assume that it may produce ugly result if we will define colors randomly](https://github.com/openvinotoolkit/open_model_zoo/pull/1897#issuecomment-742558466)

@vladimir-dudnik had an idea that someone may hardly want to see segmentation default color set used if such exists. `--colors` allows to provide it.

**Comment by vladimir-dudnik** [comment]
format description of this text file with colors is missed, there is no sample, so not clear how one can create such file

**Review by Wovchena — APPROVED** [review]

**Review by vladimir-dudnik — CHANGES_REQUESTED** [review]
can we add description of color palette file to demo rather then delete changes?

**Pull request closed without merging**
