### PR TITLE
update ref for license-plate-recognition-barrier-0007

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
update ref values for actually used synthetic dataset

### CODE REVIEW

**Comment by snosov1** [comment]
Not sure I see the point here. For one thing, synthetic dataset was used for training (in that sense we do something "anti-data-scientific" by validating and training on the same set). For the second thing, it seems unnecessarily big for validation purposes. 

What was wrong with the original set of 3K images?

**Review by eaidova — APPROVED** [review]

**Review by Anna-Mironova — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
@nosov that aligns ref metric value (used in validation) with actual state. We may return back to this after release, if you want.

**Comment by snosov1** [comment]
I see that it has to match validation. My question is why do you validate on the synthetic set (vs 3K real world images)

**Comment by vladimir-dudnik** [comment]
I think it is because you guys define validation procedure in this way, is not it? We do not invent the way how to validate models.

**Comment by snosov1** [comment]
So, it was 3K and *we* changed it to 300K?

**Comment by vladimir-dudnik** [comment]
I think it was started from 300K when model go to OMZ.

**Pull request merged**
