### PR TITLE
demos/cpp: support OpenCV3

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by Wovchena** [comment]
It is stated on wiki https://github.com/opencv/opencv/wiki/BuildOpenCV4OpenVINO

**Comment by eaidova** [comment]
> It is stated on wiki https://github.com/opencv/opencv/wiki/BuildOpenCV4OpenVINO

but people who tries to run demos in usual way does not read wiki, so it is better to provide details explicitly

**Comment by Wovchena** [comment]
The usual way is dropped. There is no OpenCV in OpenVINO now

**Comment by eaidova** [comment]
> The usual way is dropped. There is no OpenCV in OpenVINO now

not understand, how it is connected? 
I just ask highlight what if user get standard or community opencv version and compile demos, in this case, it is not possible to run GAPI demos. Right now, it is not obvious not from demos documentation, not from wiki

**Review by eaidova — APPROVED** [review]

**Pull request merged**
