### PR TITLE
tmp

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
@ivikhrev, demos builds fail: http://213.221.44.203/job/omz/job/precommit/job/cpp_demos_ubuntu18/17/console. Can you fix it?

**Comment by ivikhrev** [comment]
@Wovchena yeah, looking into it right now

**Comment by ivikhrev** [comment]
@Wovchena problem is in aligned strategy between github and gitlab. Your target branch is `releases/2021/4`, and in cpp demos job is switched to the same branch in pipeline repository, where is no script `custom_demos_ubuntu18`. In usual scenario with master all works fine- https://github.com/openvinotoolkit/open_model_zoo/pull/3366. Should we duplicate changes to the  `releases/2021/4` branch in pipeline repository?

**Comment by Wovchena** [comment]
`omz/precommit_trigger.groovy` from `releases/2021/4` doesn't now about new pipelines. Why are they triggered here?

**Comment by ivikhrev** [comment]
> omz/precommit_trigger.groovy from releases/2021/4 doesn't now about new pipelines. Why are they triggered here?

strangely, but precommit_trigger is taken from master, not from  `releases/2021/4 `.

**Comment by Wovchena** [comment]
@nignatovsky, we already had that question) How to solve this?

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by nignatovsky** [comment]
> > omz/precommit_trigger.groovy from releases/2021/4 doesn't now about new pipelines. Why are they triggered here?
> 
> strangely, but `omz/precommit_trigger.groovy` is taken from master, not from `releases/2021/4 `.

Fixed branch choosing for precommit_trigger job.

**Pull request closed without merging**
