### PR TITLE
Update the family of cross-domain reid models

### PR DESCRIPTION
**Pull request by sovrasov**
Only weights are updated, there are no major changes for now.

### CODE REVIEW

**Comment by eaidova** [comment]
@sovrasov  please do not remove old models until new have not been uploaded to OMZ yet. It can become the problem for demo testing. We remove them later, when new models package will be added

**Comment by eaidova** [comment]
Jenkins ok to test

**Comment by sovrasov** [comment]
@eaidova the only error left is a dead link in `public/resnet-50-tf/resnet-50-tf.md` should I fix it to make the CI green?

**Comment by eaidova** [comment]
> @eaidova the only error left is a dead link in `public/resnet-50-tf/resnet-50-tf.md` should I fix it to make the CI green?

@sovrasov , no, I already fix it in https://github.com/openvinotoolkit/open_model_zoo/pull/1406

**Comment by eaidova** [comment]
@sovrasov here is anoter problem in docs not connected with resnet, please add model to index.md

```
 /home/jenkins/workspace/omz/precommit/documentation_ubuntu16/jenkins/omz/scripts/documentation_check.py src/models/intel
23:22:49  person-reidentification-retail-0270 not in index.md file
```

**Pull request merged**
