### PR TITLE
[DOCS] Link adjustment for master

### PR DESCRIPTION
**Pull request by msmykx-intel**
JIRA Ticket: 110042

Update of hardcoded links to switch references from latest, nightly and 2022.3 (and earlier) to 2023.0.

### CODE REVIEW

**Comment by Wovchena** [comment]
What's wrong with `latest`? `2023.0` links are dead for now. (But I guess they won't be dead after the release publication.)

**Comment by msmykx-intel** [comment]
@Wovchena we are removing latest from documentation versioning with the 23.0 release so we are switching to hardcoded links with version number in them, hence this update.

**Comment by Wovchena** [comment]
Ok. I prefer to merge releases/2023/0 version of this patch first and after that I will merge releases/2023/0 into master. That will ensure we don't leave any commit behind. So this PR isn't needed. I will keep this PR hanging for now as a reminder for myself.

Is there a deadline for https://github.com/openvinotoolkit/open_model_zoo/pull/3770? Does @mpushki have time to fix CI?

**Comment by msmykx-intel** [comment]
Sounds great :) As for the deadline, if @mpushki could fix the CI in time to do the merge before release day that would be great :)

Btw. if you want more details on why we are removing "latest", I can forward you the latest newsletter mail from our docs team which has a brief explanation of the changes ;)

**Comment by Wovchena** [comment]
> Btw. if you want more details on why we are removing "latest", I can forward you the latest newsletter mail from our docs team which has a brief explanation of the changes ;)

Yes, please

**Comment by Wovchena** [comment]
Merged https://github.com/openvinotoolkit/open_model_zoo/pull/3772

**Pull request closed without merging**
