### PR TITLE
demos: treat warnings as errors for WIN32 by default

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by IRDonch** [comment]
The warning fix seems fine, but I'm against enabling warnings-as-errors by default. A future version of the Microsoft compiler could emit new warnings, thus making already-released code fail to build.

**Comment by Wovchena** [comment]
But for non windows branch we have the similar option set unconditionally.

**Comment by Wovchena** [comment]
It IE deprecation warnings trigger errors

**Comment by IRDonch** [comment]
> But for non windows branch we have the similar option set unconditionally.

Well, I'm against that too. :-)

**Pull request closed without merging**
