### PR TITLE
[NOTFORMERGE] Update nltk version in requirement to resolve SNYK scan

### PR DESCRIPTION
**Pull request by byungilm**
+ Clear SNYK-PYTHON-NLTK-1932014

Signed-off-by: Min, Byungil <byungil.min@intel.com>

### CODE REVIEW

**Comment by eaidova** [comment]
@byungilm please stay files in ci folder as is or use special script https://github.com/openvinotoolkit/open_model_zoo/blob/master/ci/update-requirements.py

ci folder is not a part of openvino package, it  is only OMZ precommit validation infra dependencies and they should have pinned version, relaxation (e.g. >=) are not accepted

**Comment by byungilm** [comment]
> @byungilm please stay files in ci folder as is or use special script for update https://github.com/openvinotoolkit/open_model_zoo/blob/master/ci/update-requirements.py
> 
> ci folder is not a part of openvino package, it is only OMZ precommit validation infra dependencies (should be excluded from snyk scans if I right remember) and they should have pinned version, relaxation (e.g. >=) are not accepted

Thanks for the info! I will remove the update from ci folder.
How about tools/accuracy_checker ? Does the tools have have this kind of limit?

**Comment by eaidova** [comment]
> How about tools/accuracy_checker ? Does the 'tools' have this kind of limit?

For accuracy checker, the only recommendation that version should be aligned with other openvino components, so I believe it is fine

**Comment by byungilm** [comment]
Not covered at this release. Closed.

**Pull request closed without merging**
