### PR TITLE
ci: openvino 2021.4.752

### PR DESCRIPTION
**Pull request by Wovchena**
switch public CI to the latest OpenVINO 2021.4.2 release

### CODE REVIEW

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
@nignatovsky not clear why we have: STATUS: FAILURE, RC: 1 Topology: action-recognition-0001-decoder
I did not find issues in the log

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Pull request merged**
