### PR TITLE
Added iostream include

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
And replace deprecated exception API

### CODE REVIEW

**Review by Wovchena — APPROVED** [review]

**Comment by Wovchena** [comment]
CC @ivikhrev

**Comment by Wovchena** [comment]
@ilya-lavrenov, as far, as I'm concerned, updating `ci/dependencies.yml` should fix builds: https://github.com/openvinotoolkit/open_model_zoo/pull/2334

**Review by IRDonch — APPROVED** [review]
Thanks, just in time. :-)

**Comment by IRDonch** [comment]
Hmm, OK, I see the problem. We need to simultaneously update OpenVINO and apply these fixes.

@ilya-lavrenov I think I'll cherry-pick your commit into my update branch. I'll keep this PR open for now as a reminder.

**Comment by ivikhrev** [comment]
@ilya-lavrenov I was going to do the same, but you did it first:)
So I when I made fixes, I noticed that macros[ THROW_IE_EXCEPTION](https://github.com/openvinotoolkit/open_model_zoo/blob/9ca5dbeff80464bf5728e8be25daedfe9a9208d7/demos/common/cpp/utils/include/utils/common.hpp#L269) also used deprecated exception API, why you didn't replace it with IE_THROW() ?

**Comment by ivikhrev** [comment]
And what about `InferenceEngine::IInferRequest`, `ExecutableNetwork::CreateInferRequestPtr,` `InferenceEngine::make_so_pointer`  ? Compiler showed warnings about them too. 
```
warning C4996: 'InferenceEngine::IInferRequest': Do not use IInferRequest API
 
warning C4996: 'InferenceEngine::make_so_pointer': Use std::make_shared<Extension>
 
warning C4996: 'InferenceEngine::ExecutableNetwork::CreateInferRequestPtr': Use ExecutableNetwork::CreateInferRequest instead
```

**Comment by ivikhrev** [comment]
> @ilya-lavrenov I was going to do the same, but you did it first:)
> So when I made fixes, I noticed that macros[ THROW_IE_EXCEPTION](https://github.com/openvinotoolkit/open_model_zoo/blob/9ca5dbeff80464bf5728e8be25daedfe9a9208d7/demos/common/cpp/utils/include/utils/common.hpp#L269) also uses deprecated exception API, why you didn't replace it with `IE_THROW()` ?

We decided to replace macro `THROW_IE_EXCEPTION` with `std::runtime_error`, see #2343. It's non-issue now.

**Comment by ilya-lavrenov** [comment]
> And what about `InferenceEngine::IInferRequest`, `ExecutableNetwork::CreateInferRequestPtr,` `InferenceEngine::make_so_pointer` ? Compiler showed warnings about them too.
> 
> ```
> warning C4996: 'InferenceEngine::IInferRequest': Do not use IInferRequest API
>  
> warning C4996: 'InferenceEngine::make_so_pointer': Use std::make_shared<Extension>
>  
> warning C4996: 'InferenceEngine::ExecutableNetwork::CreateInferRequestPtr': Use ExecutableNetwork::CreateInferRequest instead
> ```

I don't have a goal to refactor OMZ with new API. The only thing I need is to add iostream include to a proper file (otherwise it blocks another PR to openvino itself). I kept only this change and reverted others.

All other changes like removing usage of deprecated API are supposed to be done by OMZ team.

**Pull request merged**
