### PR TITLE
Fix the out of memory error in FramesThreadBody

### PR DESCRIPTION
**Pull request by nixingyang**
This pull request solves https://github.com/openvinotoolkit/open_model_zoo/issues/1578.

### CODE REVIEW

**Comment by DmitriySidnev** [comment]
:+1:

**Comment by eaidova** [comment]
Jenkins ok to test

**Comment by eaidova** [comment]
@nixingyang  thank you for your patch!
@DmitriySidnev, I right understand, do you accept these changes?

**Comment by DmitriySidnev** [comment]
@eaidova, yes we discussed it and also I tried the demo with this update, so it fixes the bug.

**Comment by eaidova** [comment]
> @eaidova, yes we discussed it and also I tried the demo with this update, so it fixes the bug.

ok, nice job 👍 :) Then I merge.

**Review by eaidova — APPROVED** [review]

**Pull request merged**
