### PR TITLE
Submitting two models for chest x-ray screening

### PR DESCRIPTION
**Pull request by Rakshith2597**
Submitting two models for chest x-ray screening. The first model employs DenseNet-121 CNN architecture. The second CNN model was obtained by performing a systematic search over a set of CNN architectures obtained by scaling the width and depth of DenseNet using the EfficientNet method.

This is part of the project MIRIAD: Many Incarnations of Screening of Radiology for High Throughput Disease Screening via Multiple Instance Reinforcement Learning with Adversarial Deep Neural Networks, sponsored by INTEL TECHNOLOGY INDIA PVT. LTD.

Principal Investigators:

Dr Debdoot Sheet (PI), Dr Nirmalya Ghosh (Co-PI)
Department of Electrical Engineering
Indian Institute of Technology Kharagpur

Dr Ramanathan Sethuraman (Co-PI)
Intel Technology India Pvt. Ltd.

Dataset used: 2018 RSNA Pneumonia detection challenge dataset
[Dataset License](https://www.rsna.org/-/media/Files/RSNA/Education/AI-resources-and-training/AI-image-challenge/pneumonia-detection-challenge-terms-of-use-and-attribution.ashx?la=en&hash=FF7A635F6DFFAD31A30C8715DFA3B8FC21131543)

### CODE REVIEW

**Comment by Rakshith2597** [comment]
`If a model uses a dataset which is not supported by the Accuracy Checker, you also must provide the license and the link to it and mention it in the PR description.` 

Since the above line is mentioned in the documentation Accuracy-checker.yml is not provided.
The Dataset used: 2018 RSNA Pneumonia detection challenge dataset
[Dataset License](https://www.rsna.org/-/media/Files/RSNA/Education/AI-resources-and-training/AI-image-challenge/pneumonia-detection-challenge-terms-of-use-and-attribution.ashx?la=en&hash=FF7A635F6DFFAD31A30C8715DFA3B8FC21131543)

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Open Model Zoo models downloader does not work this way. Please create a subfolder with desired model name in <OMZ>/models/public. This subfolder should have the following files: README.md, model.yml, accuracy-check.yml (you may refer to any other public model for an example). Each OMZ public model located in its corresponding subfolder, we do not support more then one model in subfolder.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Review by vladimir-dudnik — CHANGES_REQUESTED** [review]
@Rakshith2597 please pay attention to failed pre-commit checks. There are number of trailing whitespaces and download of chest-xray-screening-eff failed, because of link to google drive points to .PTH file but seems you expect to download .ONNX file (size is different)

**Pull request closed without merging**
