### PR TITLE
add write logs to file, summary of failures, timeout for subprocess in run_tests.py

### PR DESCRIPTION
**Pull request by ivikhrev**
Added ability to write demos logs to file, set timeout for subprocess to 10 minutes, and sum up failures at the end.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@Wovchena @nignatovsky @ivikhrev BTW, added output log looks useful, would it be possible to modify CI job in the way to store these logs as job artifacts (so usual log still be short is it is now but we have ability to look at stored detailed log(s) in job artifacts)?

**Comment by nignatovsky** [comment]
> @Wovchena @nignatovsky @ivikhrev BTW, added output log looks useful, would it be possible to modify CI job in the way to store these logs as job artifacts (so usual log still be short is it is now but we have ability to look at stored detailed log(s) in job artifacts)?

Yes, we just need to add **archiveArtifacts** command to groovy scripts.

**Review by Wovchena — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
where is summary on failrures, on linux log I see just: 19:11:50  2 failures:

**Comment by ivikhrev** [comment]
> where is summary on failrures, on linux log I see just: 19:11:50 2 failures:

I'm figuring this out.

**Comment by ivikhrev** [comment]
@vladimir-dudnik fixed
```
21:10:02  2 failures:
21:10:02  Test case #0/CPU:
21:10:02  /jenkins/workspace/omz/precommit/demos_ubuntu18@2/venv/bin/python /jenkins/workspace/omz/precommit/demos_ubuntu18@2/src/demos/image_retrieval_demo/python/image_retrieval_demo.py -d CPU --no_show -g /mnt/datasets/Image_Retrieval/gallery.txt -i /mnt/datasets/Image_Retrieval/4946fb41-9da0-4af7-a858-b443bee6d0f6.mp4 -m /tmp/tmp9jrkz3xg/models/intel/image-retrieval-0001/FP16/image-retrieval-0001.xml -u cdm
21:10:02  Exit code: 1
21:10:02  
21:10:02  Test case #1/CPU:
21:10:02  /jenkins/workspace/omz/precommit/demos_ubuntu18@2/venv/bin/python /jenkins/workspace/omz/precommit/demos_ubuntu18@2/src/demos/image_retrieval_demo/python/image_retrieval_demo.py -d CPU --no_show -g /mnt/datasets/Image_Retrieval/gallery.txt -i /mnt/datasets/Image_Retrieval/4946fb41-9da0-4af7-a858-b443bee6d0f6.mp4 -m /tmp/tmp9jrkz3xg/models/intel/image-retrieval-0001/FP16-INT8/image-retrieval-0001.xml -u cdm
21:10:02  Exit code: 1
```

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Pull request merged**
