### PR TITLE
Added CNN models for Musculoskeletal Radiograph Screening

### PR DESCRIPTION
**Pull request by arunava555**
This code is based on our workshop paper in NeurIPS 2019  where we had compared different CNN architectures to identify the joint or bone type as well as detect the presence of abnormalities in Musculoskeletal X-ray images.

The paper is available at: 

https://profs.etsmtl.ca/hlombaert/public/medneurips2019/66_CameraReadySubmission_Musculoskeletal_cameraready_MedNeurIPS.pdf

### CODE REVIEW

**Comment by eizamaliev** [comment]
Please, use `develop` branch instead of `master`

**Comment by vladimir-dudnik** [comment]
First of all, thanks for your intention to contribute to OpenVINO Open Model Zoo. We are appreciate that and want to help your PR went smoothly through contribution review process. We apply certain requirements to the content of Open Model Zoo and expect external contributors will accept and comply with them. The basic requirements to contribution are documented at CONTRIBUTING.md file, it might still not contain all requirements, although we working on improvement of documentation. So, I'll provide comments below.

All models in Open Model Zoo are subject of regular validation which includes conversion to OpenVINO IR with every OpenVINO release, running model and demo accuracy and performance validation. As such, for model contribution, we need to consider validation dataset availability and license. We do not redistribute datasets, but keep and use them internally during regular validation cycles. Obviously, validation dataset license should not conflict with Open Model Zoo license.

Please provide link to LUNA validation dataset, so we may review the license applied and judge if we can accept your PR.
@yssemaev FYI

**Comment by arunava555** [comment]
Hi,

In my request to contribute the OpenVino model, I have employed the MURA
dataset (not LUNA) for Musckuloskeletal_Radiograph_Classification. This
dataset is publicly available under "Stanford University School of Medicine
MURA Dataset Research Use Agreement" and is freely available for research
and non-commercial use. The details of the dataset license is available in
the webpage: https://stanfordmlgroup.github.io/competitions/mura/   (please
look at the end of the webpage).

Please advise if I need to modify the license of our OpenVino model and
which license can be used?

Thanks and Regards,
Arunava

**Comment by vladimir-dudnik** [comment]
model license is Apache 2.0 and it is ok, but it seems dataset license requirements contradict with Apache 2.0 terms, so we can't accept PR with such license.

**Pull request closed without merging**
