### PR TITLE
Python demos: update API configuration 

### PR DESCRIPTION
**Pull request by anzhella-pankratova**
Rename `set_config->set_property`

### CODE REVIEW

**Review by Wovchena — APPROVED** [review]

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
You have a conflict now

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Pull request merged**
