### PR TITLE
cpp object detection demo: add faceboxes wrapper

### PR DESCRIPTION
**Pull request by ivanvikhrev**
Add cpp wrapper for faceboxes-pytorch model.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Review by vladimir-dudnik — COMMENTED** [review]
do you really need double floating point precision in intermediate computations?

**Comment by ivanvikhrev** [comment]
> do you really need double floating point precision in intermediate computations?

I've just rechecked and it is possible to make anchors calculations in int and float. I'll fix it.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a built

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Review by vladimir-dudnik — APPROVED** [review]

**Pull request merged**
