### PR TITLE
Fixing headers and links in Datasets.

### PR DESCRIPTION
**Pull request by sgolebiewski-intel**
This PR addresses CVS-86927.

Hyperlinks are not rendered when used as a sole text in headers. 
Additionally, it appears that using nested markdown (backquotes within square brackets in hyperlinks) also is problematic

image

### CODE REVIEW

**Comment by kblaszczak-intel** [comment]
Could we have links to the pages moved under the headers? Something like:

## ImageNET
See the [ImageNet home page](http://image-net.org)

This way we can be sure not to lose the link... I would prefer to unify the "how to download" sections to include "go to www" as step 1. But it may be a future improvement.

Also, we could improve language a bit while we're at it :) For example, "To download WIDER Face dataset:" seems enough as a call to action.

**Comment by sgolebiewski-intel** [comment]
> Also, we could improve language a bit while we're at it :) For example, "To download WIDER Face dataset:" seems enough as a call to action.

I'm thinking about removing even such sentences, since step 1 reads: "Go to .... website" or "Download ... ". 

Of course that would not apply to such cases as ImageNet, where there's info about registering etc.

**Comment by sgolebiewski-intel** [comment]
I went for "unifying 'how to download' sections to include 'go to www' as step1" where possible. So all the links to home pages/websites have been brought back.

**Review by kblaszczak-intel — APPROVED** [review]
Great! Looks nice.

**Review by AdamTumi — APPROVED** [review]

**Pull request merged**
