### PR TITLE
social_distance: downgrade frameCounter to 32-bit

### PR DESCRIPTION
**Pull request by Wovchena**
Follow up https://github.com/openvinotoolkit/open_model_zoo/pull/2071

### CODE REVIEW

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by ivikhrev** [comment]
Is it needed to replace all `uint64_t` types with `uint32_t` or only those are used as std::atomic? And in this demo we also have 
`std::vector<std::atomic<int64_t>> lastProcessedIds;`. Is this needed to be replaced also?

**Comment by Wovchena** [comment]
The problem is about making 64 bit var atomic on 32 bit system.
Replaced

**Comment by ivikhrev** [comment]
> Is it needed to replace all uint64_t types with uint32_t or only those are used as std::atomic? And in this demo we also have
> std::vector<std::atomic<int64_t>> lastProcessedIds;. Is this needed to be replaced also? Because if we are going to make lastProcessedIds as int32_t, we will have to make all ids as int32_t.

updated

**Comment by ivikhrev** [comment]
> Because if we are going to make lastProcessedIds as `int32_t`, we will have to make all ids as `int32_t`.

Others ids are int64_t, so there would be comparison between `int32_t` and `int64_t`.
` return lastProcessedFrameId == sharedVideoFrame->frameId;`

**Comment by Wovchena** [comment]
Well, it is able to cast them. And https://github.com/openvinotoolkit/open_model_zoo/blob/12e8e4f3bd194e5307d48469721a1982efcd61ee/demos/common/cpp/pipelines/include/pipelines/async_pipeline.h#L85 uses int64_t.

I think the question is wider: what type to use to count frames. int64_t probably isn't friendly to 32 bit system even when it's not atomic. Though I won't answer it in this PR :)

**Review by ivikhrev — APPROVED** [review]

**Pull request merged**
