### PR TITLE
Published 1st set of candidate models for 2022.1 Release

### PR DESCRIPTION
**Pull request by nignatovsky**

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
waiting actual model uploading

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Jenkins ok to test

**Comment by vladimir-dudnik** [comment]
smartlab models should be updated

**Comment by Wovchena** [comment]
Their status is Release, not Release-External

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Review by jkamelin — COMMENTED** [review]
Paths to vocabs should also be updated
https://github.com/openvinotoolkit/open_model_zoo/blob/bb8acdb7b136027b41586aa9ecb185e8409862cf/demos/tests/cases.py#L748

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Review by anzhella-pankratova — APPROVED** [review]

**Pull request merged**
