### PR TITLE
Make quantizer.py work on yolo_v4_tf model

### PR DESCRIPTION
**Pull request by henry1758f**
yolo_v4_tf **model.yml** missing "quantizable" parameter,
it will make tools/quantizer.py skip the quantization with following message.

> ========== Skipping yolo-v4-tf (quantization not supported)

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
please re-target your PR to develop branch according to requirements in [CONTRIBUTING.md](https://github.com/openvinotoolkit/open_model_zoo/blob/master/CONTRIBUTING.md)

**Comment by eaidova** [comment]
@henry1758f , thank you, we have plans to extend list of quantizible model in OMZ with providing proper configuration for them and yolo-v4 included (cc @Anna-Mironova ), so it will be available soon.

**Comment by vladimir-dudnik** [comment]
@henry1758f we will extend number of quantized model (including yolo-v4) in this [PR](https://github.com/openvinotoolkit/open_model_zoo/pull/2365).

**Comment by eaidova** [comment]
@henry1758f  now PR with inclusion yolo_v4 to quantization is merged, so I'm closing your PR

**Pull request closed without merging**
