### PR TITLE
Define armv7 instruction set for OMZ demos built natively on x32 ARM

### PR DESCRIPTION
**Pull request by alvoron**
Fix to https://github.com/openvinotoolkit/open_model_zoo/pull/2641
It sets `armv7` instruction set to x32 only. The previous PR treats `ARM64` architecture which is used in Apple M1 chip incorrectly.

### CODE REVIEW

**Review by Wovchena — APPROVED** [review]

**Comment by Wovchena** [comment]
Please retarget this to release after https://github.com/openvinotoolkit/open_model_zoo/pull/2653

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by alvoron** [comment]
> Please retarget this to release after #2653

Do you mean I need to update this PR to target it to release branch or create a dedicated PR to release branch (as we did with the previous fix)?

**Comment by Wovchena** [comment]
You need to update this PR to target it to release branch. Last time the decision about having it in release was made after it was merged.

**Comment by vladimir-dudnik** [comment]
something is wrong, there should not be so many changes for such simple fix

**Pull request closed without merging**
