### PR TITLE
Cast mask type as FP32

### PR DESCRIPTION
**Pull request by eugene123tw**

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Jenkins please retry a build

**Comment by Wovchena** [comment]
Well, we can't really test [releases/2022/SCv1.1](https://github.com/openvinotoolkit/open_model_zoo/tree/releases/2022/SCv1.1) now

**Comment by Wovchena** [comment]
Not now :)

**Comment by vladimir-dudnik** [comment]
@Ilya-Krylov can you create PR to master branch first, so we can at least built and test. It anyway should be back ported to master, so make sense

**Comment by eugene123tw** [comment]
Hi @vladimir-dudnik at the moment Ilya doesn't have access, so perhaps I could help. Basically, make a new PR but based on master, right?

**Comment by akorobeinikov** [comment]
> Hi @vladimir-dudnik at the moment Ilya doesn't have access, so perhaps I could help. Basically, make a new PR but based on master, right?

I created PR #3457  to master, but CI doesn't work anyway now.

**Comment by eugene123tw** [comment]
@akorobeinikov do you have an estimation of when will the CI come back again?

**Pull request merged**
