### PR TITLE
remove old machine translation, correct device support

### PR DESCRIPTION
**Pull request by eaidova**
removed GPU  support due to zero accuracy on FP16 model

### CODE REVIEW

**Review by Anna-Mironova — APPROVED** [review]

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
@eaidova seems we need to remove and models itself to make precommit doc check happy

**Comment by vladimir-dudnik** [comment]
cc @Wovchena

**Comment by eaidova** [comment]
> @eaidova seems we need to remove and models itself to make precommit doc check happy

sorry, forgot to add them to commit

**Comment by Anna-Mironova** [comment]
Remove please symbolic links to AC configs for these models

**Pull request merged**
