### PR TITLE
Merge releases/2023/0 into master

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by eaidova** [comment]
@Wovchena @mpushki looks like some inconsistency in package versions on jenkins, instead of new changes, it tests changes in package for downloader job:

18:08:18    File "/opt/home/sys_k8sworker/workspace/omz/precommit/downloader_ubuntu20/venv/lib/python3.8/site-packages/openvino/model_zoo/models/public/efficientdet-d1-tf/pre-convert.py", line 34, in main
18:08:18      subprocess.run([sys.executable, '--',
18:08:18    File "/usr/lib/python3.8/subprocess.py", line 512, in run
18:08:18      raise CalledProcessError(retcode, process.args,
18:08:18  subprocess.CalledProcessError: Command '['/opt/home/sys_k8sworker/workspace/omz/precommit/downloader_ubuntu20/venv/bin/python3', '--', '/tmp/model-downloads/public/efficientdet-d1-tf/model/model_inspect.py', '--runmode=saved_model', '--model_name=efficientdet-d1', '--ckpt_path=/tmp/model-downloads/public/efficientdet-d1-tf/efficientdet-d1', '--saved_model_dir=/tmp/model-downloads/public/efficientdet-d1-tf/efficientdet-d1_saved_model']' returned non-zero exit status 2.

it exact what I change in my commit (I remove this file in my patch), could you please verify the correctness and order of installing packages?

**Review by eaidova — APPROVED** [review]

**Comment by Wovchena** [comment]
@mpushki, please, take a look

**Comment by mpushki** [comment]
> @mpushki, please, take a look

I will check

**Comment by mpushki** [comment]
Jenkins job [omz_converter.py](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/model_tools/src/openvino/model_zoo/omz_converter.py)
[pre-convert.py](https://github.com/openvinotoolkit/open_model_zoo/blob/d32664908bea6f76d4ae83869ebb0ec18336027c/tools/model_tools/src/openvino/model_zoo/omz_converter.py#L36) is used inside.
on my side - I use `filter = '--list=tested_models.lst'` from [omz repo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/model_tools/tests/representative-models.lst).

**Comment by Wovchena** [comment]
This PR removes mentioned `pre-convert.py` for `efficientdet-d0-tf`. Yet it is executed. That shouldn't happen

**Pull request merged**
