### PR TITLE
Update requirements-tensorflow.in

### PR DESCRIPTION
**Pull request by metr0jw**
Added pyyaml>=5.4.1 to requirements at tools/downloader/requirements-tensorflow.in

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
16:25:13  tools/downloader/requirements-tensorflow.in:2: last line doesn't end with a newline character

**Comment by metr0jw** [comment]
Oops that was a mistake

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by jkamelin** [comment]
Why is this changes needed? We have pyyaml>=5.4.1 in [tools/downloader/requirements.in](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/tools/downloader/requirements.in#L1), which is the requirements for tools. And `requirements-tensorflow.in` contains additional dependencies for converting Tensorflow models.

**Comment by metr0jw** [comment]
> Why are this changes needed? We have pyyaml>=5.4.1 in [tools/downloader/requirements.in](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/tools/downloader/requirements.in#L1), which is the requirements for tools. And `requirements-tensorflow.in` contains additional dependencies for converting Tensorflow models.

I guess I was out of my mind I didn't check the README properly.
Close PR.

**Pull request closed without merging**
