### PR TITLE
demos/tests: suppress broken G-API

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by dmatveev** [comment]
Wow! There's full dedicated workflow to test the G-API demos now.. That's so cool, thanks so much folks! 💖

**Comment by Wovchena** [comment]
Thank you for thanks :)

**Comment by dmatveev** [comment]
@Wovchena so what particular demos are broken, could you please provide details so we look on that?

**Comment by Wovchena** [comment]
I've reported them to @TolyaTalamanov. Everything marked with `# TODO: enable after https://github.com/TolyaTalamanov fixes G-API` in https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/tests/cases.py:
1. classification_benchmark_demo (subset of models)
2. gesture_recognition_demo
3. smart_classroom_demo

**Pull request merged**
