### PR TITLE
Fix plugin bug in object detection demo

### PR DESCRIPTION
**Pull request by junwenwu**
In the Python demo, the argument -device can only take AUTO because of the previous bug inside of the async_pipeline.py script. Updated the script so it can handle the device configuration correctly.

### CODE REVIEW

**Comment by openmodelzooci** [comment]
Can one of the admins verify this patch?

**Comment by Wovchena** [comment]
Wasn't it fixed by https://github.com/openvinotoolkit/open_model_zoo/pull/3936?

**Comment by junwenwu** [comment]
#3936 introduced a bug. config is initialized as an empty dict and then 'device' is used as a key to reference the empty dictionary and causes error. This is trying to fix this bug.

**Review by Wovchena — APPROVED** [review]
Thank you

**Pull request merged**
