### PR TITLE
segmentation_demo.py: load default Pascal palette from file 

### PR DESCRIPTION
**Pull request by anzhella-pankratova**
The purpose is to not keep this palette in SegmentationVisualizer class itself, but load colors from file in palettes folder, representing this palette.
Also, rendering is updated in order to decrease the latency of rendering time (80ms->10ms)

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@anzhella-pankratova what is the purpose of this change? There will no default palette anymore and you'll have to provide one as a file (yet another mandatory param)?

**Comment by anzhella-pankratova** [comment]
> @anzhella-pankratova what is the purpose of this change? There will no default palette anymore and you'll have to provide one as a file (yet another mandatory param)?

@vladimir-dudnik The behavior of the demo is not changed: if one does not provide any color palette, the demo will take colors from Pascal VOC dataset palette by default, the argument `--colors` is still optional.
The purpose is to not keep this palette in `SegmentationVisualizer` class itself, but load colors from file in `palettes` folder, representing this palette.

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
@anzhella-pankratova should not we check if file not found by default path (for example demo copied out to another place)?

**Comment by anzhella-pankratova** [comment]
> should not we check if file not found by default path (for example demo copied out to another place)?

In this case `get_palette_from_file()` will accept the non-existent file and raise `FileNotFoundError`, trying to open it. So I think the failure message by  the error is enough here

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Comment by anzhella-pankratova** [comment]
Jenkins please retry a build

**Review by Wovchena — APPROVED** [review]

**Pull request merged**
