### PR TITLE
Added VOC2007 dataset, changed VOC2012 to VOC2007 for public models

### PR DESCRIPTION
**Pull request by Anna-Mironova**
- Added dataset to dataset_definitions.yml
- Updated docs and accuracy results for mobilenet-ssd, ssd300, ssd512, yolo-v1-tiny-tf public models
- Updated dataset preparation guide, included VOC2007 dataset for object detection task

### CODE REVIEW

**Comment by Anna-Mironova** [comment]
Jenkins please retry a build

**Comment by eaidova** [comment]
@vshampor just FIY

**Comment by eaidova** [comment]
@Anna-Mironova please also update dataset preparation guide to include VOC2007 for object detection

**Review by IRDonch — APPROVED** [review]

**Review by vladimir-dudnik — APPROVED** [review]

**Review by eaidova — APPROVED** [review]

**Comment by eaidova** [comment]
Jenkins please retry a build

**Pull request merged**
